base_url: http://localhost:3000
terrain_url: http://terrain
listen_port: 3000

logging:
    level: info
    label: sonora server

db:
    host: localhost
    port: 5432
    user: null
    password: null
    database: de

sessions:
    secret: "keyboard cat"
    secure_cookie: false
    ttl: 8
    poll_interval_ms: 5000

keycloak:
    server_url: "https://kc.cyverse.org/auth"
    realm: "CyVerse"
    client_id: null
    client_secret: null

intercom:
    app_id: appId
    enabled: true
    company_id: DE-DEV
    company_name: DISCOVERY ENVIRONMENT

admin:
    groups: some-group
    group_attribute_name: entitlement

irods:
    home_path: /iplant/home

fileIdentifier:
  htPathList: "# application/vnd.de.path-list+csv; version=1"
  multiInputPathList: "# application/vnd.de.multi-input-path-list+csv; version=1"
